spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/ostock_dev
    password: postgres
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
example:
  property: I AM DEV
