spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/ostock_dev
    password: postgres
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
example:
  property: I AM DEV

resilience4j:
  circuitbreaker:
    instances:
      licenseService:
        register-health-indicator: true
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.lang.Throwable
          - java.io.IOException
          - java.util.concurrent.TimeoutException
      organizationService:
        sliding-window-size: 5
        register-health-indicator: true
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.lang.Throwable
          - java.io.IOException
          - java.util.concurrent.TimeoutException
