spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    show-sql: 'true'
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/ostock_dev
    password: postgres
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    platform: postgres
  database:
    driverClassName: org.postgresql.Driver
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
example:
  property: I AM DEV

server:
  port: 8081
